### ISSUE TITLE
CAN reliability improvements

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/lib-common#125]
- If you run `examples/can_print_tx` but don't connect CAN to another board, it keeps printing `ERR: No ack.`. We need to make sure this doesn't infinite loop if CAN transmission fails (it should time out at some point). Maybe this happens when the TX error count is 127?

**Comment by jackberezny** [comment]
This issue should be resolved with #144, as the bus will turn off after the transmit error counter reaches 255.
