### ISSUE TITLE
Clean up the branches on lib-common

### ISSUE THREAD

**Issue by vogeldylan** [HeronMkII/lib-common#15]
Not sure which features are still under development; Cleaning up the branches would help to clarify this.

**Comment by siddMahen** [comment]
Cleaned up all the branches I've pushed. Only remaining branches are from PAY @brunofalmeida but I think they're still being used.

**Comment by brunofalmeida** [comment]
I'm currently working on `pay-can-dev-2`, will create a PR after testing it with what I'm working on in the `pay` repository.

**Comment by brunofalmeida** [comment]
@siddMahen Have you considered deleting `code-cleaning` and `dev_branch_demo`?

**Comment by siddMahen** [comment]
Git tells me that the branch contains commits that aren't referenced in any other branch, so I want to review those before deleting

**Comment by siddMahen** [comment]
Same with `uart-wip`.

**Comment by brunofalmeida** [comment]
What are the `obc-dev` and `uart-wip` branches intended for? They haven't been committed to since September.

**Comment by siddMahen** [comment]
@brunofalmeida I think `obc-dev` is Ali's. Git tells me I shouldn't delete `uart-wip` because it contains commits that aren't referenced in any other branch. I'm pretty sure it can be deleted, but I want to make sure I'm not losing anything important. Will figure this out in a little bit.

**Comment by siddMahen** [comment]
I think for the time being, the branch list is sufficiently small that it won't matter anyways.

**Comment by siddMahen** [comment]
@vogeldylan Can I close this? I think we're basically done.

**Comment by vogeldylan** [comment]
Done.
