### ISSUE TITLE
Get more accurate restart reason information

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/lib-common#154]
From [here](http://web.engr.oregonstate.edu/~traylor/ece473/lectures/reset.pdf), the MCUSR register can give us more information on the cause of reset. That might be for a different AVR model but it should be similar for ours.

<img width="905" alt="Screen Shot 2019-07-11 at 19 42 16" src="https://user-images.githubusercontent.com/13157832/61092409-20512200-a414-11e9-9383-cb02bc8cfbd9.png">

**Comment by Tahreeem** [comment]
- commit c0df728246ff20eae43225f29513bac6aca4ad82 on branch more-restart-reasons
- above needs testing
