### ISSUE TITLE
Multi-board testing for make harness command

### ISSUE THREAD

**Issue by jackberezny** [HeronMkII/lib-common#159]
Currently, the "make harness" command only has support for the automatic detection of a single port. We either want to be able to specify the detection of a higher number of programming and uart ports when required or automatically detect all connected MCUs for multi-board testing.

See: 
`harness:
$(PYTHON) ./bin/harness.py -p $(PORT) -u $(UART) -d $(TEST) $(HARNESS_ARGS)`

https://github.com/HeronMkII/lib-common/blob/master/makefile

**Comment by brunofalmeida** [comment]
I thought about this, but think it makes more sense to explicitly specify the ports in the case of multi-board testing so you know which program is uploaded to which board. I updated the makefiles to pass PORT2 and UART2 arguments to the `harness.py` script.
