### ISSUE TITLE
raw_input() vs input()

### ISSUE THREAD

**Issue by Tahreeem** [HeronMkII/lib-common#35]
Line 43:
``ans = raw_input("Run test suite '%s'? (y/n) " % suite.name)``

Line 53:
``ok = raw_input("Connect the UART TX pin(s) to SCK. (ok) ")``

These two lines use raw_input() function which works for python 2.x but not for python 3.x. For python 3.x, the correct function is input(). So people using the different versions need note.

**Comment by siddMahen** [comment]
See #36
