### ISSUE TITLE
TypeError: unicode strings are not supported, please encode to bytes

### ISSUE THREAD

**Issue by Tahreeem** [HeronMkII/lib-common#37]
Line 59, 66, 70 and 225 produce that error on Windows.

The fix is simple. For example for Line 59:
``ser.write("COUNT\r\n")``
Changing it to the following fixed the problem:
``temp = "COUNT\r\n"``
``ser.write(temp.encode())``

**Comment by siddMahen** [comment]
@Tahreeem what happens when you change `ser.write("COUNT\r\n")` to `ser.write(b"COUNT\r\n")`? I believe this should fix the problem.

**Comment by siddMahen** [comment]
Also, I doubt its a Windows error; most likely a python 3 error.

**Comment by siddMahen** [comment]
@Tahreeem what's the status on this issue? Did the above comment work?

**Comment by Tahreeem** [comment]
@siddMahen I downloaded Python 2 today and didn't get that error so I'm guessing that was a Python 3 related problem.

**Comment by siddMahen** [comment]
It's definitely a python 3 related issue; could you try running the code with Python 3 and the changes I suggested and let me know if it works?

**Comment by Tahreeem** [comment]
I'll be in the lab on Thursday again. Will try with Python 3 too then and let you know of the errors tied to that.

**Comment by siddMahen** [comment]
@Tahreeem Let me know if this works

**Comment by Tahreeem** [comment]
I tried ``ser.write(b"COUNT\r\n")`` format yesterday but still got the same error: ``ValueError: invalid literal for int() with base 10''. I left windows at that...

**Comment by siddMahen** [comment]
Ok, but you didn't get the error `TypeError: unicode strings are not supported`, so that's an improvement. The invalid literal business is a windows problem, unfortunately.

**Comment by Tahreeem** [comment]
Hmm yes, the TypeError is resolved at this point.

**Comment by siddMahen** [comment]
To confirm, the TypeError is gone when tested with Python 3?

**Comment by Tahreeem** [comment]
Yes. Both formats resolve the TypeError.

**Comment by siddMahen** [comment]
Fixed in #43 .

**Comment by palaniappanece** [comment]
import time
import serial

print("Starting program")

ser = serial.Serial("/dev/ttyUSB0", baudrate=9600,
                    parity=serial.PARITY_NONE,
                    stopbits=serial.STOPBITS_ONE,
                    bytesize=serial.EIGHTBITS
                    )
time.sleep(1)
try:
    temp="hello world"
    ser.write(temp.encode())
    #ser.write("Serial Communication Using Raspberry Pi\r\n")
    #ser.write("By: Embedded Laboratory\r\n")
    print("Data Echo Mode Enabled")
    while True:
        if ser.inWaiting() > 0:
            data = ser.read()
            print(str(data))

except KeyboardInterrupt:
    print("Exiting Program")

**Comment by palaniappanece** [comment]
this program works in python3 to read and write the data from the serial port

**Comment by palaniappanece** [comment]
library is sudo apt-get install python3-serial
