### ISSUE TITLE
RFC: Test harness should support Python 3.x exclusively

### ISSUE THREAD

**Issue by siddMahen** [HeronMkII/lib-common#38]
I think there are too many fundamental differences between Python 2.x and Python 3.x to write the test harness script cleanly for both platforms.

Looking into the future, Python 3.x is the way to go. It improves on every aspect of Python 2.x and introduces very useful new features. I think we should drop support for Python 2.x.

@alihaydaroglu @Tahreeem @BrytniR @brunofalmeida Thoughts?

**Comment by brunofalmeida** [comment]
I don't have a preference between Python 2/3 but I agree that it's better to just design the test harness for one version.

**Comment by alihaydaroglu** [comment]
i agree
