### ISSUE TITLE
Running test harness

### ISSUE THREAD

**Issue by RebeccaShemesh** [HeronMkII/lib-common#39]
This is how I found the ports I needed to use:
<img width="463" alt="screen shot 2018-06-18 at 3 02 48 pm" src="https://user-images.githubusercontent.com/39317766/41556637-5f6caa46-7309-11e8-8020-801cd2021da4.png">

This is how I ran test harness:
<img width="750" alt="screen shot 2018-06-18 at 3 04 53 pm" src="https://user-images.githubusercontent.com/39317766/41556686-80834f46-7309-11e8-9d8c-f727b83c1974.png">

And this is the error we kept getting. We tried playing around with it but aren't too sure what it means:
<img width="527" alt="screen shot 2018-06-18 at 3 05 07 pm" src="https://user-images.githubusercontent.com/39317766/41556718-93f7615c-7309-11e8-8e28-219fefcb3d41.png">

**Comment by siddMahen** [comment]
Hmm that's very strange. The way the test harness works is that the 32m1 tells the harness how many tests it going to run, this is called the `count`, and then the harness tells it exactly when to start each test, and it does this `count` number of times. It seems like the test harness is having trouble parsing the `count` value returned by the 32m1.

This seems like it might be a problem with the UART on the board; were you using new boards?

Also, was this run on a Windows or a Mac? @RebeccaShemesh

**Comment by RebeccaShemesh** [comment]
We managed to get arithmetic and print to run, but when we tried spi this came up:
<img width="518" alt="screen shot 2018-06-19 at 7 14 45 pm" src="https://user-images.githubusercontent.com/39317766/41629035-550d6a08-73f5-11e8-892d-09e7ac5b5123.png">

**Comment by RebeccaShemesh** [comment]
Also, we realized that the previous issue we had was because none of the main files (also print and arithmetic) had init_uart() in main.

**Comment by siddMahen** [comment]
init_uart is already called by the testing library internally; it shouldn't be required to print anything

**Comment by siddMahen** [comment]
@RebeccaShemesh closing this now because I think it's been resolved. Let me know if it needs to be opened again for whatever reason.
