### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by RebeccaShemesh** [HeronMkII/lib-common#40]
When we try to run the spi, uart, and can tests it doesn't recognize any of the functions. This is the error we keep getting:

<img width="576" alt="screen shot 2018-06-19 at 9 29 52 pm" src="https://user-images.githubusercontent.com/39317766/41632438-ef25440a-7407-11e8-95aa-126a4f920c08.png">

@siddMahen

**Comment by siddMahen** [comment]
Fixed in #43 .
