### ISSUE TITLE
Multi-board example test gives none-type attribute error after completion

### ISSUE THREAD

**Issue by jackberezny** [HeronMkII/lib-common#41]
![image](https://user-images.githubusercontent.com/33333774/41815727-57d4866e-7741-11e8-88b1-6461a8713a5c.png)

Test finishes (and passes), but throws an exception before advancing to the next test (mac). All other tests (including other multi-board tests) do not have this error.

**Comment by jackberezny** [comment]
![image](https://user-images.githubusercontent.com/33333774/41815777-97a714e0-7742-11e8-91eb-6e4ce3dfb074.png)

Upon further inspection, it appears as if line 13 of main1.c should be 
"run_tests(suite,1)" instead of "run_tests(suite, 2)".

**Comment by siddMahen** [comment]
Nice sleuthing; thanks

**Comment by siddMahen** [comment]
Fixed in #43 .
