### ISSUE TITLE
Unexpected USB port Mac (Test Harness)

### ISSUE THREAD

**Issue by jackberezny** [HeronMkII/lib-common#42]
![image](https://user-images.githubusercontent.com/33333774/41815749-9ff3c57c-7741-11e8-9556-2fb0e0ad8e0c.png)

/dev/tty.usbmodem8 and /dev/tty.usbmodem9 showed up instead of the expected /dev/tty.usbmodem00xxxxxx ports. This was incompatible with the test harness, as the usb port numbers were only separated by one instead of two. Resetting the PRAM and replacing the cable fixed this issue, but the cause is still unclear.

**Comment by siddMahen** [comment]
Wow, strange!

**Comment by siddMahen** [comment]
Let me know if this happens again, and if so, write down any details that you think might help me reproduce this problem.
