### ISSUE TITLE
Queue and stack assertion testing

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/lib-common#47]
On the `queue-stack-assert` branch, the `examples/queue_echo` and `examples/stack_echo` programs that test the `queue` and `stack` libraries need to be moved to the `tests` folder and converted to use assertion-based testing with the test harness.

https://github.com/HeronMkII/lib-common/pull/28
https://utat-space-systems.gitbooks.io/heron-mk-ii/content/software-tools/test-harness.html

**Comment by siddMahen** [comment]
Am working on this; see #56 @Alireza1997

**Comment by siddMahen** [comment]
Completed in #56 .
