### ISSUE TITLE
Watchdog timer and heartbeat integration

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/lib-common#48]
On the `watchdog` branch:
- The `watchdog` library needs to be cleaned up and documented more
- The `func_tests/watchdog_test` test needs to be cleaned up, run on its own, and verified for correctness
- Develop a new test that integrates watchdog with heartbeat, i.e. use watchdog to reset the microcontroller and heartbeat to recover the state

**Comment by brunofalmeida** [comment]
It's the watchdog development task

**Comment by jackberezny** [comment]
Points one and two should be be resolved when https://github.com/HeronMkII/lib-common/pull/76 is merged. Note that the func_test is now a part of the test harness suite.

**Comment by brunofalmeida** [comment]
The core watchdog library is done, see #69 for heartbeat integration.
